name: Rebelmonster
favicon: null
layout_spectrum: 0.14390224404633045
typography_spectrum: 0.5821887527126819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2853862203191966
  lightness: 0.004842519527301192
  saturation: 0.46673905197530985
  rhythmicContrast: 0.6653527265880257
purpose: []
