name: Retrofitweho
favicon: null
layout_spectrum: 0.29397
typography_spectrum: 0.48396
title: Retrofitweho.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c6d6f'
    - '#ffffff'
    - '#f9b530'
    - '#d5d5d5'
    - '#a5a5a5'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
